# Generated by Django 2.0.2 on 2018-04-13 19:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 13, 19, 5, 35, 352753, tzinfo=utc), verbose_name='Request Time'),
        ),
    ]
