# Generated by Django 2.0.2 on 2018-04-16 13:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20180413_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=500, verbose_name='Request Description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Complaint_owner', to=settings.AUTH_USER_MODEL)),
                ('owner2', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Complaint_owner2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(default='', max_length=50)),
                ('First_Name', models.CharField(default='', max_length=50)),
                ('Last_Name', models.CharField(default='', max_length=50)),
                ('Country', models.CharField(default='', max_length=200)),
                ('CommissionStatus', models.CharField(default='', max_length=200)),
                ('Age', models.CharField(max_length=500)),
                ('gender', models.CharField(default='', max_length=50)),
                ('Profile', models.ImageField(upload_to='media')),
                ('owner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Info_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=500, verbose_name='Request Description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Review_owner', to=settings.AUTH_USER_MODEL)),
                ('owner2', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Review_owner2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='owner2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ArtWork_owner2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 16, 13, 7, 5, 302582, tzinfo=utc), verbose_name='Request Time'),
        ),
    ]
